name: Go CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable' # or specific version like '1.21'

      - name: Check out code
        uses: actions/checkout@v4

      - name: Get dependencies
        run: go mod tidy
      - name: Verify dependencies
        run: go mod verify

      - name: Run tests
        run: go test -v ./...

      - name: Run linting (optional)
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64

  release:
    name: Release
    needs: test
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for semantic-release

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 17
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
